drop table if exists admin_user CASCADE;
drop table if exists company CASCADE;
drop table if exists stock CASCADE;
drop table if exists dividends CASCADE;
drop table if exists admincompany CASCADE;

create table admin_user (
    id bigint generated by default as identity,
    user_id varchar(100),
    password varchar(255),
    org_name varchar(200),
    company_code varchar(100),
    create_at timestamp,
    expired_at timestamp,
    primary key (id)
);

create table company (
   company_code varchar(100),
   company_name varchar(200),
   primary key (company_code)
);

create table admin_company (
    id bigint generated by default as identity,
    admin_user_id bigint NOT NULL,
    company_code varchar(100) NOT NULL,
    primary key (id)
);
create table dividends (
   id bigint generated by default as identity,
   amount numeric(19, 2),
   start_at timestamp,
   expired_at timestamp,
   primary key (id)
);

create table stock (
    id bigint generated by default as identity,
    stock_name varchar(100),
    stock_type varchar(100),
    company_code varchar(100),
    primary key (id)
);